# A basic apache server. To use either add or bind mount content under /var/www
FROM docker.elastic.co/kibana/kibana:6.4.0

MAINTAINER John Hudson version: 0.1
ADD kibana.yml /usr/share/kibana/config/
