# A basic apache server. To use either add or bind mount content under /var/www
FROM httpd:2.4

MAINTAINER John Hudson version: 0.1



ADD index.html /usr/local/apache2/htdocs/
ADD httpd.conf /usr/local/apache2/conf/httpd.conf
