- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host key_ecs_instances:!tag_aws_autoscaling_groupName_ecs_cluster
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: filebeat-ubuntu
    - role: hosts

- hosts: key_ecs_instances:!tag_Name_ecs_node
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: datadog-docker


- hosts: key_ecs_instances:!tag_aws_autoscaling_groupName_ecs_cluster  tag_Name_core_bastion_host tag_Name_ecs_bastion_host key_core_instances:!tag_Application_GoCD_agent
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
#    - role: freeipa-client



- hosts: tag_Name_core_gocd_agent_ansible_1 tag_role_core_gocd_agent
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"

  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packer
    - role: dhcp-revert

- hosts: tag_Application_second_reading
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: filebeat-bitnami-wordpress
