- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host key_ecs_instances

  vars:
#    shortname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
#    domain: "parliament.uk"

    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      expvar_port: 5050
      cmd_port: 5051
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: filebeat-ubuntu
    - role: hosts

- hosts: key_ecs_instances  tag_Name_core_bastion_host tag_Name_ecs_bastion_host key_core_instances
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: freeipa-client



- hosts: tag_Name_core_gocd_agent_ansible_1
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"

  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packer




- hosts: tag_role_core_gocd_agent

  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: npm-login



- hosts: tag_InstallNode_yes
  vars:
    NODEJS_VERSION: "8"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: nodejs

- hosts: tag_InstallRuby_yes
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: ruby
